### ISSUE TITLE
Node placement problem

### ISSUE THREAD

**Issue by sebastiancarlsson** [d3/d3-sankey#2]
Hello,

I'm trying to create a chart with this library but for some reason some nodes get placed a bit weirdly, please see the screenshot. I'd expect the B and F node to be placed further down so that they don't overlap the other elements (since there's plenty of space for that). I basically copied the example, styled it, and replaced the data with my own, otherwise the example code is intact. Not sure if this is a bug or if there's some reason why the chart is drawn like this. I'd be happy to try to fix it and submit a PR but I just wanted to confirm that this behaviour is not by design before I give it a shot. Thank you

![screen shot 2016-04-15 at 15 28 48](https://cloud.githubusercontent.com/assets/713106/14562750/d160acd6-031e-11e6-9dae-ea908fb070b1.png)

My data:

```
var data = {
  nodes:[
    {name:"A"},
    {name:"B"},
    {name:"C"},
    {name:"D"},
    {name:"E"},
    {name:"F"},
    {name:"G"}
  ],
  links:[
    {source:0, target:1, value:100},
    {source:0, target:2, value:200},
    {source:1, target:3, value:40},
    {source:1, target:2, value:40},
    {source:1, target:6, value:20},
    {source:2, target:4, value:200},
    {source:2, target:5, value:40},
    {source:5, target:6, value:40},
  ]
}
```

**Comment by tenshis** [comment]
+1

I'm interested in a solution to this problem as well.

**Comment by TheBiro** [comment]
I came with a solution that I'm still working on, but it is a specific to the problem you have.

The idea is to change the "class" attribute to all nodes, so you can manually change its position.

For example:
- Links class: `.attr("class", function(d) { return "link " + d.source.name + " " + d.target.name; })`
- Nodes class: `.attr("class", function(d) { return "node " + d.name; })`

Now you can change the position on the .css.

PS: I'm really new to html, css and js programming (less than 4 months). If this is not recommended I'll be pleased to know.

**Comment by mbostock** [comment]
This library performs relaxation in passes of alternating directions, from right-to-left and then left-to-right. When relaxing from left-to-right, it moves each node’s following nodes (the targets of the node’s source links) towards the node’s center; for example, it tries to center B around the center of A. Likewise when relaxing from right-to-left, it moves each node’s preceding nodes (the sources of the node’s target links) towards the node’s center; for example, it tries to center B around the weighted average centers of C, G and D.

In this example, the primary problem is the left-to-right place, where it moves the center of B up towards the center of A. (There’s a similar but lesser problem moving the center of B up towards the center of C as part of the right-to-left pass, but it’s mitigated because the weighted average center of C, G and D is used.)

A better heuristic would probably try to contain B within the span of A on the left-to-right pass (and similarly for the right-to-left pass), but simply changing to that heuristic instead of the move-to-center heuristic does not work well because it greatly increases the overlap between links. Currently, there is no penalty when a link passes through a node, such as the link from B to G that passes through C.

Fixing this problem in general requires a more thorough redesign of how the layout is optimized. It might also require the insertion of dummy nodes, so that when a link spans more than one topological layer (such as B→G), it can be routed through a dummy node to avoid overlap with other nodes in the intermediate layers (such as B→*dummy*→G, where the *dummy* then avoids collision with C).

So, the short summary of this issue is “the generated layout could be better” and the answer is “yes, but it’s hard”, and I may get around to working on it sometime in the future but I don’t have a concrete plan for doing so in the short term, and so I’m going to close this issue. However, contributions for better layout heuristics and algorithms are welcome!
