### ISSUE TITLE
Link path with gradient is not visible

### ISSUE THREAD

**Issue by wiesson** [d3/d3-sankey#28]
I'm new to d3 and I mostly played with the sankey example and filled it with my own data. Further, I took this example https://bl.ocks.org/micahstubbs/3c0cb0c0de021e0d9653032784c035e9 and applied it to the latest version of Mike Bostocks example.

In some cases, my gradient will not be rendered and I'm wondering why. 
Here is a live example: https://bl.ocks.org/wiesson/87c7714081e1b1f24e5b36b4335b09c2

Here is an example image:
![missing-link](https://cloud.githubusercontent.com/assets/933231/26832534/1dfe2b5a-4ad0-11e7-939d-60e9d2926980.png)

If I do a minor change to the path:

```
M487.5,53.92715034058265
M487.5,53.92714034058265 // 53.92715 vs 53.92714
``` 
it will render as desired. Whats wrong here? If I remove the gradient, it works perfectly. I also tried to round the value from `73.45653630669118` to `70` but no difference.

**Comment by mbostock** [comment]
This is an unfortunate limitation of SVG’s design; the default gradientUnits = objectBoundingBox, and when the path is horizontal, the bounding box is degenerate (height = zero) because the bounding box does not consider the stroke.

The “easiest” fix is to gradientUnits = userSpaceOnUse, but then you have to compute the coordinates of the gradient relative to the SVG container rather than using the local coordinates of the path.

Or, you could compute the outline of the path yourself by computing the offset Bézier—not trivial! [Bezier.js](https://pomax.github.io/bezierjs/) might help with that.

Or, you could special-case horizontal lines and draw a rect instead of a line, or some such.

In the future, please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗

**Comment by wiesson** [comment]
Thank you very much for your answer. I did a quick fix, with userSpaceOnUse, but I will maybe just draw a rect to avoid this problem at all.

Quickfix:
```javascript
if(d.y1 - d.y0 === 0) {
    linearGradient.attr('gradientUnits', "userSpaceOnUse")
}
```

**Comment by mbostock** [comment]
That fix probably isn’t sufficient because you’ll need to specify different coordinates for the gradient when you switch to userSpaceOnUse.

**Comment by wiesson** [comment]
Yes I know - but the color is at least visible! 😅 (despite being wrong / incorrect).

**Comment by yrokhlin** [comment]
For any future googlers such as myself that may stumble upon this problem, I found a neat little hack that will let you get around this issue.

```
.attr('d', d3.sankeyLinkHorizontal())
.attr('d', (d, i, items) => {
    const path = d3.select(items[i]).attr('d');
        return path + ' l0,0.00001';
    })
```

This takes your `d` attribute after you set it with `d3.sankeyLinkHorizontal()` and adds a small string at the end which basically just picks up the last point of the path and slightly jitters it on the `y` axis. This makes it so `d.y1 - d.y0 === 0` will never be `true` and the jitter is visually imperceivable.

I think this is a better solution than creating a `rect` especially if you are doing any sort of highlighting. 

I hope this helps someone else out who is stuck.

**Comment by Jrubzjeknf** [comment]
@yrokhlin's solution didn't work for me, so based on his solution I modify the calculated path.

```typescript
      .attr('d', sankeyLinkHorizontal())
      .attr('d', (_, i, items) => {
        const path = select(items[i]).attr('d');
        const match = path.match(/,([^C]+)C/);

        if (match.length !== 2) {
          return path;
        }

        const replacementValue = +match[1] + 0.01;
        const fixedPath = path.replace(match[1], '' + replacementValue);

        return fixedPath;
      })
```

This turns `M16,352.50000000000005C249.66666666666666,etc..` into `M16,352.51000000000005C249.66666666666666,etc..`.

**Comment by ekatzenstein** [comment]
Yeah this feels silly, but here's a function for making it work with paths that are not necessarily two points:

```    const dehorizontalize = (path) => {
      // https://github.com/d3/d3-sankey/issues/28
      const splitPath = path.split(" ");
      const last = splitPath[splitPath.length - 1];
      const newLast = last;
      splitPath[splitPath.length - 1] = +newLast + 1;
      return splitPath.join(" ");
    };```

**Comment by ivanjermakov** [comment]
For me issue was that I had spaces in gradient id so it was not picking up correctly.

**Comment by Nikolay-Uvarov** [comment]
Hello everyone, still have the same issue. 
I used @Jrubzjeknf approach and got the following: 
![image](https://github.com/d3/d3-sankey/assets/22148553/76e4d6e6-edf5-40f9-9fcf-ca9f5d3dda70)
