### ISSUE TITLE
Cannot use with Browserify?

### ISSUE THREAD

**Issue by guypursey** [d3/d3-sankey#30]
I've been trying to use NPM to import `d3-sankey` into a visualisation I've been working on.

Either the documentation isn't clear or I'm going about this incorrectly.

The readme file recommends:

```
<script src="https://unpkg.com/d3-sankey@0"></script>
<script>

var sankey = d3.sankey();

</script>
```

However, this does not allow the kind of version control I want to use via `package.json` and Browserify.

So I have resorted to using this in my main JavaScript file:

```
var d3 = require("d3")
var sankey = require("d3-sankey").sankey
var sankeyLinkHorizontal = require("d3-sankey").sankeyLinkHorizontal

```
When I try to call `d3.sankey()` as recommended in the documentation, this obviously won't work.

So I have to use `sankey = sankey()` and so on instead...

I'm concerned I'm missing out on some key functionality by not having these as methods of `d3` and by having separate callouts for `sankey` and `sankeyLinkHorizontal` -- though it could be that the issue I'm having with `sankeyLinkHorizontal` is unrelated.

In any case, some clearer documentation about the relationship between the plugin and D3 and how one might use in a Browserify situation would be a welcome change. 

Hope this feedback helps!

**Comment by guypursey** [comment]
It could just be that the documentation/readme needs to advise something like the following:

```
var d3 = require("d3")
d3.sankey = require("d3-sankey").sankey
d3.sankeyLinkHorizontal = require("d3-sankey").sankeyLinkHorizontal
```

**Comment by mbostock** [comment]
This is the expected behavior, and is true of all [D3 modules](https://github.com/d3), not just d3-sankey.

If you’re using the CommonJS API—which is primarily intended for Node—when you require a d3 module, you get back whatever symbols that module exports on an object specific to that module. So if you `require("d3-sankey")`, you get an object with a sankey and a sankeyLinkHorizontal property. This object is different from the object returned by `require("d3")`.

There are two patterns are recommend for CommonJS. The first is to declare separate objects:

```js
var d3 = require("d3"),
    d3_sankey = require("d3-sankey");
```

In this case, it may be better to use the D3 modules separately rather than mixing the default bundle with the submodules:

```js
var d3_selection = require("d3-selection"),
    d3_sankey = require("d3-sankey");
```

The second pattern is to merge into a single object using Object.assign:

```js
var d3 = Object.assign({}, require("d3"), require("d3-sankey"));
```

Note however that the second pattern does not preserve live bindings, and so will not work with [d3.event](https://github.com/d3/d3-selection/blob/master/README.md#event).

The exported symbol `sankey` is documented as `d3.sankey` in the API reference for simplicity; it’s how you refer to it in vanilla JavaScript, and it’s to indicate that the D3 modules share a namespace dictated by support for vanilla JavaScript and the shared `d3` global. Depending on which pattern you use in CommonJS, you might refer to it `d3.sankey` or `d3_sankey.sankey` or whatever symbol you define it as on import.

I could drop the “d3.” prefix from the README, but then it becomes harder to distinguish between symbols that are exported by the library and interfaces that are defined by the library (such as *sankey*.nodeWidth, where the italics indicate an interface or class).

If you’re using the ES6 API, then you can import whatever symbols you like directly:

```js
import {sankey} from "d3-sankey";
```

**Comment by mbostock** [comment]
Also note that you can require a specific version, or version range, of d3-sankey from unpkg if you desire. For example:

```html
<script src="https://unpkg.com/d3-sankey@0.6.1"></script>
```

**Comment by guypursey** [comment]
Thanks for getting back to this so quickly and for updating the readme.

The key line in your comment above for me was "I could drop the `d3.` prefix from the README, but then it becomes harder to distinguish between symbols that are exported by the library" -- I think for me it was just about clarity. If requiring the module rather than using a unpkg.com hotlinking then one needs to explicitly assign the `sankey` and `sankeyLinkHorizontal` properties to those names under `d3` in order for your mention of `d3.sankey()` to work.

That's why I just went with this in the end:

```
d3.sankey = require("d3-sankey").sankey
d3.sankeyLinkHorizontal = require("d3-sankey").sankeyLinkHorizontal
```

You can see that in action on this [work in progress](http://bl.ocks.org/guypursey/dd592bd1afaee74db173e404e421e876).

Great work on all of this by the way!

**Comment by mbostock** [comment]
An equivalent shorthand of your approach would be:

```js
var d3 = Object.assign(require("d3"), require("d3-sankey"));
```

This will copy everything from d3-sankey onto the object returned by requiring d3. (And this approach will work with d3.event, since that’s on the first object passed to Object.assign.)
