### ISSUE TITLE
Sankey with Typescript

### ISSUE THREAD

**Issue by tboehnisch** [d3/d3-sankey#37]
I installed d3 and d3-sankey, including their @types with via npm. If I do:

import * as d3 from 'd3';
import * as dd3 from 'd3-sankey';

.....
var sankey = d3.sankey()
    .nodeWidth(15)
    .nodePadding(10)
    .extent([[1, 1], [width - 1, height - 6]]);

I cant get I running, it's not recognizing sankey() as a method on d3.

Uncaught (in promise): TypeError: Cannot read property 'getAttribute' of null TypeError: Cannot read property 'getAttribute' of null at Selection.selection_attr [as attr] 
...

**Comment by mbostock** [comment]
Sorry, but I don’t maintain TypeScript bindings. But my guess is that you want to do something like:

```js
import * as d3_sankey from "d3-sankey";

var sankey = d3_sankey.sankey();
```

**Comment by tomwanzek** [comment]
@tboehnisch As @mbostock  pointed out, the TS definitions for d3-sankey are written to support straightforward TypeScript module import/export syntax. I.e. in your above code snippet, it should work as long as you use `dd3.sankey()` given the import alias `dd3` you used, instead of `d3.sankey()`.

Alternatively, you can of course use the alternative `import {sankey, SankeyLayout} from 'd3-sankey'` etc.
I am using the definitions in both these ways, albeit usually with not in combination with the default `d3` bundle, but individual `d3-xxxx` modules.
