### ISSUE TITLE
Dataflow tooltips are not working on touch devices

### ISSUE THREAD

**Issue by JaniKarh** [d3/d3-sankey#5]
This is a "general" D3.js issue, but would it be possible to fix this for d3-sankey specifically, since it's quite vital for readability? Demo e.g. http://bl.ocks.org/xaranke/9ada4c74a87b57ae7308

**Comment by mbostock** [comment]
This issue is not specific to d3-sankey or even to d3; it’s an issue with SVG and accessibility. The [energy flow example](https://bl.ocks.org/mbostock/ca9a0bb7ba204d12974bca90acc507c0) uses [SVG title elements](https://www.w3.org/TR/SVG/struct.html#DescriptionAndTitleElements). You can use JavaScript for different tooltips if you prefer.

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Although I make an effort to assist everyone that asks, I am not always available to provide help promptly or directly. Stack Overflow provides a better collaborative forum for self-help: tens of thousands of D3-related questions have already been asked there, and some answered questions may be relevant to you.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
