### ISSUE TITLE
Property 'Sankey' doesn't exist on @types/d3

### ISSUE THREAD

**Issue by sam-sams** [d3/d3-sankey#69]
d3.sankey()function doesn't exist in d3 package, even though I have installed d3-sankey package.

import * as d3 from 'd3';
import { sankey as Sankey } from 'd3-sankey';

 var sankey = d3
            .sankey()
            .nodeWidth(15)
            .nodePadding(10)
            .extent([1, 1], [dimensions.innerWidth - 1, dimensions.innerHeight - 6]);

**Property 'sankey' does not exist on type 'typeof import("/node_modules/@types/d3/index")'.**

**Comment by mbostock** [comment]
I think you mean to call `sankey = Sankey()` rather than `sankey = d3.sankey()`?

Please use [Stack Overflow tag d3.js](https://stackoverflow.com/tags/d3.js) to ask for help. Stack Overflow provides a better collaborative forum: thousands of D3-related questions have been asked there, and some answers may be relevant to you.

When asking for help, please include a link to demonstrate the issue, preferably as an [Observable notebook](https://beta.observablehq.com). It is often impossible to debug from code snippets alone. Isolate the issue and reduce your code as much as possible before asking for help. The less code you post, the easier it is for someone to debug, and the more likely you are to get a helpful response.

If you have a question about D3’s behavior and want to discuss it with other users, also consider the [d3-js Google Group](https://groups.google.com/forum/#!forum/d3-js) or [joining](https://d3-slackin.herokuapp.com/) the [d3-js Slack](https://d3js.slack.com/).

Thank you! 🤗
